version: '2'
services:
  app:
    build: .
    restart: always
    ports:
    - 5000:5000
  db:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_PASSWORD=todoapi
      - POSTGRES_USER=todoapi