name: Pull request labeler

on: [ pull_request_target ]

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          leaflet-secret: ${{ secrets.LEAFLET_ACCESS_TOKEN }}
          realm-secret: ${{ secrets.REALM_APP_ID }}
          default-cdn-secret: ${{ secrets.DEFAULT_CDN }}

